name: build-exe

on:
  push:
    tags: [ 'v*' ]       
  release:
    types: [created]      
  workflow_dispatch:      

permissions:
  contents: write        

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # .NET 9 preview kurulumu
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'     # ← önemli

    # tek dosya exe üret
    - name: Publish single-file exe
      run: dotnet publish MethodExporter.csproj -c Release -r win-x64 `
          --self-contained true /p:PublishSingleFile=true -o publish

    # Release’e yükle
    - name: Upload exe to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: publish/*.exe
